config/routes.rb
Spree::Core::Engine.routes.draw do

  namespace :api, defaults: {format: 'json'} do
    resources :line_items do
      member do
        delete :remove_add_ons
      end
    end
  end

  namespace :admin do
    resources :add_ons
  end
end

app/models/spree/add_on.rb
module Spree
  class AddOn < Spree::Base
    acts_as_paranoid

    include Spree::CalculatedAdjustments

    validates :calculator, presence: true, if: :is_master?
    validates :name, presence: true, if: :is_master?
    validates :sku, presence: true, uniqueness: true, if: :is_master?
    validates :active, presence: true, if: :is_master?

    after_save :touch_products

    scope :active, -> { where(active: true) }
    scope :master, -> { where(is_master: true, master_id: nil) }

    # Spree relations
    has_one :line_item, through: :adjustment, as: :source
    has_one :adjustment, as: :source, dependent: :destroy
    has_many :images, as: :viewable, dependent: :destroy, class_name: "Spree::AddOnImage"
    has_and_belongs_to_many :products

    # Self polymorphic(?) relation yo
    # master is the AddOn itself
    # option is a child AddOn that contains the stored option_value/input(?) for the add on
    belongs_to :master, class_name: "#{self.to_s}"
    has_many :options, class_name: "#{self.to_s}", foreign_key: "master_id"

    delegate :adjust, :compute_amount, to: :adjuster

    accepts_nested_attributes_for :images, :allow_destroy => true

    cattr_accessor :permitted_values
    self.permitted_values = Set.new

    def adjuster
      @adjuster ||= Spree::AddOnAdjuster.new(self)
    end

    def master
      if is_master?
        self
      else
        # unscope for relations
        self.class.unscoped { super }
      end
    end

    def attach_add_on(line_item, values = {})
      new_add_on = create_option(values)
      adjustment = adjuster.adjust(line_item)

      if adjustment.present?
        adjustment.source = new_add_on
        adjustment.save!
      end
    end

    def values
      preferences
    end

    def values=(props)
      props.keys.each do |key|
        if has_preference? key.to_sym
          set_preference(key.to_sym, props[key])
        end
      end
    end

    def as_json(opts = {})
      super(opts.merge(
                only: Spree::Api::ApiHelpers.add_on_attributes,
                methods: [:values],
                include: [:images]
            )
      )
    end

    def self.display_name
      'Basic'
    end

    private

    def create_option(values)
      master.options.create!({
                                 type: type,
                                 master: master,
                                 name: master.name,
                                 values: values
                             })
    end

    def touch_products
      products.each(&:touch)
    end

  end
end

app/models/spree/add_on/gift_wrapping.rb
require_dependency 'spree/add_on'

module Spree
  class AddOn::GiftWrapping < Spree::AddOn
    # define the options for this add on via preferences
    preference :color, :string

    self.permitted_values << :color

    def self.display_name
      'Gift Wrapping'
    end

    def colors
      %W(red, blue, green)
    end

    private

    def valid_pref
      errors.add(:preferred_color, "invalid color") unless colors.include? preferred_color
    end

  end
end

app/controllers/spree/admin/add_ons_controller.rb
module Spree
  module Admin
    class AddOnsController < ResourceController
      before_action :load_data

      def location_after_save
        edit_object_url(@add_on)
      end

      def show
        redirect_to edit_object_url(@add_on)
      end

      private

      def load_data
        @calculators = Rails.application.config.spree.calculators.add_ons
      end
    end
  end
end

app/views/spree/admin/add_ons/_form.html.erb
<% content_for :page_actions do %>
    <%= button_link_to(Spree.t(:new_image), 'javascript:void(0);', {class: "btn-success", icon: 'add', id: 'new_add_image_link'}) if can? :create, Spree::Image %>
<% end %>

<div data-hook="admin_tax_category_form_fields">
  <div class="row">
    <div class="omega six columns">
      <%= f.field_container :name do %>
          <%= f.label :name, Spree.t(:name) %>
          <%= f.text_field :name, :class => 'fullwidth', placeholder: 'Add On name' %>
      <% end %>
    </div>
    <div class="omega four columns">
      <%= f.field_container :sku do %>
          <%= f.label :sku, "SKU" %><br>
          <%= f.text_field :sku, :class => 'fullwidth', placeholder: 'ABC-123' %>
      <% end %>
    </div>
    <div class="two columns omega">
      <%= f.field_container :active do %>
          <%= f.label :active, "Active" %><br>
          <%= f.check_box :active, {}, "true", "false" %>
      <% end %>

      <%= f.hidden_field :is_master, value: true %><br>
    </div>
  </div>

  <div class="row">
    <div class="four columns omega">
      <%= f.field_container :type do %>
          <%= f.label :type, Spree.t(:type) %>
          <%= f.select :type, options_for_select(Spree::AddOn.subclasses.collect { |klass| [klass.display_name, klass.name] }, selected: @add_on.class.name), {}, :class => 'select2 fullwidth' %>
      <% end %>

      <% field_name = "[add_on][calculator_type]" %>
      <%= label_tag field_name, Spree.t(:calculator) %>
      <%= select_tag field_name, options_from_collection_for_select(@calculators, :to_s, :description), :class => 'type-select select2 fullwidth' %>
    </div>

    <% if @add_on.calculator.present? %>
        <div class="add-on-calculator field omega four columns">
          <% param_prefix = "add_on" %>
          <% type_name = @add_on.calculator.type.demodulize.underscore %>
          <% if lookup_context.exists?("fields", ["spree/admin/promotions/calculators/#{type_name}"], true) %>
              <%= render "spree/admin/promotions/calculators/#{type_name}/fields", calculator: @add_on.calculator, prefix: param_prefix %>
          <% else %>
              <%= render "spree/admin/promotions/calculators/default_fields", calculator: @add_on.calculator, prefix: param_prefix %>
          <% end %>
          <%= hidden_field_tag "#{param_prefix}[calculator_attributes][id]", @add_on.calculator.id %>
        </div>
    <% end %>

    <% unless @add_on.new_record? %>
        <%= render "spree/admin/add_ons/#{@add_on.class.to_s.demodulize.underscore}" %>
    <% end %>
  </div>

  <div class="row">
    <div class="eight columns omega">
      <%= f.field_container :description do %>
          <%= f.label :description, "Description" %><br>
          <%= f.text_area :description, class: "fullwidth", placeholder: 'Something about this add on' %>
      <% end %>
    </div>
  </div>

  <div class="add_on_images">
    <%= f.fields_for :images, @add_on.images do |img| %>
        <div class="current_image">
          <% if img.object.attachment.present? %>
              <div data-hook="thumbnail" class="add-on-option-image">
                <%= image_tag img.object.attachment.url(:small) %>
                <%= img.check_box '_destroy' %>
              </div>
          <% end %>
        </div>
    <% end %>
  </div>
</div>

<script type="text/template" id="add_on_image_form">
  <div class="current_image">
    <div data-hook="file" class="field add_on_image_form">
      <label for="add_on_images_attributes_{{count}}_attachment">Filename</label><br>
      <input id="add_on_images_attributes_{{count}}_attachment" name="add_on[images_attributes][{{count}}][attachment]" type="file">
      <input id="add_on_images_attributes_{{count}}_viewable_id" name="add_on[images_attributes][{{count}}][viewable_id]" type="hidden" value="<%= @add_on.id %>">

      <div class="actions">
        <!--<a class="add-add-on-image fa fa-edit no-text with-tip" href="javascript:void(0);"></a>-->
        <a class="cancel-add-on-image fa fa-cancel no-text with-tip hidden" href="javascript:void(0);"></a>
      </div>
    </div>
  </div>

</script>

<script>
    $(document).ready(function () {
        var currentImageCount = <%= @add_on.images.count%>,
                new_image = $('#new_add_image_link'),
                image_container = $('.add_on_images'),
                img_form = $("#add_on_image_form").html();

        new_image.on('click', function () {
            var template = Handlebars.compile(img_form);
            image_container.append(template({count: currentImageCount}));
            currentImageCount++;
            setuplisteners();
        });

        function setuplisteners() {
            var cancel = $('.cancel-add-on-image');
            cancel.on('click', function () {
                $(this).parent().parent().remove();
                currentImageCount--;
            })
        }
    })
</script>

<style>
    .add-on-option-image > img {
        max-height: 75px;
    }
</style>

app/views/spree/admin/add_ons/_gift_wrapping.html.erb
TODO

app/views/spree/admin/add_ons/edit.html.erb
<%= render 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
    Editing Add On: <%= @add_on.name %>
<% end %>

<% content_for :page_actions do %>
    <li><%= link_to_with_icon 'arrow-left', "Back to Add Ons", admin_add_ons_path, :class => 'button' %></li>
<% end %>


<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @add_on } %>

<%= form_for [:admin, @add_on.becomes(Spree::AddOn)], :html => { :multipart => true }  do |f| %>
    <% f.object = @add_on.becomes(@add_on.class) %>
    <fieldset class="no-border-top">
      <%= render :partial => 'form', :locals => { :f => f } %>
      <div class="clear"></div>
      <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
    </fieldset>
<% end %>

app/views/spree/admin/add_ons/index.html.erb
<%= render 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
    Add On
<% end %>

<% content_for :page_actions do %>
    <ul class="actions inline-menu">
      <li>
        <%= button_link_to "New Add On", new_object_url, :icon => 'plus', :id => 'admin_new_add_ons_link' %>
      </li>
    </ul>
<% end %>

<% if @add_ons.present? %>
    <table class="index">
      <colgroup>
        <col style="width: 15%;">
        <col style="width: 10%;">
        <col style="width: 48%;">
        <col style="width: 10%;">
        <col style="width: 17%;">
      </colgroup>
      <thead>
      <tr data-hook="admin_add_ons_index_headers">
        <th>SKU</th>
        <th colspan="2">Name</th>
        <th>Type</th>
        <th>Active</th>
      </tr>
      </thead>
      <tbody>
      <% @add_ons.each do |add_on| %>
          <tr id="add_on_<%= add_on.id %>">
            <td class="align-center"><%= add_on.sku %></td>
            <td class="align-center">
              <% if add_on.images.present? %>
                  <%= image_tag add_on.images.first.attachment.url(:small) %>
              <% else %>
                  No Image
              <% end %>
            </td>
            <td><%= add_on.name %></td>
            <td class="align-center"><%= add_on.class.display_name %></td>
            <td class="align-center"><%= add_on.active %></td>
            <td class="actions" data-hook="admin_products_index_row_actions">
              <%= link_to_edit add_on, :no_text => true %>
              <%= link_to_delete add_on, :no_text => true %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% else %>
    <div class="alpha twelve columns no-objects-found">
      <%= Spree.t(:no_resource_found, resource: I18n.t(:other, scope: 'activerecord.models.spree/add_on')) %>,
      <%= link_to Spree.t(:add_one), spree.new_admin_add_on_path %>!
    </div>
<% end %>

app/views/spree/admin/add_ons/new.html.erb
<%= render 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
    Create new Add On
<% end %>

<% content_for :page_actions do %>
    <li><%= link_to_with_icon 'arrow-left', "Back to Add Ons", admin_add_ons_path, :class => 'button' %></li>
<% end %>


<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @add_on } %>

<%= form_for [:admin, @add_on] do |f| %>
    <fieldset class="no-border-top">
      <%= render :partial => 'form', :locals => { :f => f } %>
      <%= render :partial => 'spree/admin/shared/new_resource_links' %>
    </fieldset>
<% end %>